<?php
/** @var array{css:?string,js:?string} $assets */
/** @var array<int, array<string, string>> $navigation */
/** @var array<string, mixed>|null $vehicle */
/** @var array<string, mixed> $data */
/** @var array<string, string> $errors */
/** @var array<string, array<int, array<string, mixed>>> $options */
/** @var array<string, mixed>|null $onboarding */
$editing = $vehicle !== null;
$value = static fn (string $field, mixed $default = ''): mixed => $data[$field] ?? $default;
$select = static function (string $field, array $items) use ($value): string {
    $html = '<option value="">Choose</option>';
    foreach ($items as $item) {
        $selected = (int) $value($field) === (int) $item['id'] ? ' selected' : '';
        $html .= '<option value="' . (int) $item['id'] . '"' . $selected . '>' . esc($item['name']) . '</option>';
    }
    return $html;
};
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title><?= $editing ? 'Edit' : 'Add' ?> Vehicle | FleetOS</title><?php if ($assets['css'] !== null): ?><link rel="stylesheet" href="/build/<?= esc($assets['css'], 'attr') ?>"><?php endif; ?></head><body class="fleet-shell"><a class="skip-link" href="#main-content">Skip to main content</a><div class="app-frame import-frame"><?= view('fleet_command_center/components/navigation', ['items' => $navigation]) ?><main id="main-content" class="command-main import-main" tabindex="-1">
<header class="top-status"><div><p class="eyebrow">Fleet / Vehicles</p><h1><?= $editing ? 'Edit Vehicle' : 'Add Vehicle' ?></h1><p class="status-copy">FleetOS identity and normalized vehicle specification.</p></div><a class="action-link" href="/fleet/vehicles">Back to vehicles</a></header>
<?php if ($onboarding !== null): ?><section class="section tone-info"><div class="section-heading"><p class="eyebrow">Discovered from Turo</p><h2><?= esc((string) $onboarding['vehicle_name']) ?></h2></div><dl class="issue-facts"><div><dt>Turo vehicle ID</dt><dd><?= esc((string) $onboarding['turo_vehicle_id']) ?></dd></div><div><dt>Year</dt><dd><?= esc((string) ($onboarding['year'] ?? 'Not provided')) ?></dd></div><div><dt>Make / model</dt><dd><?= esc(trim((string) ($onboarding['make'] ?? '') . ' ' . (string) ($onboarding['model'] ?? ''))) ?: 'Not provided' ?></dd></div><div><dt>Affected rows</dt><dd><?= (int) $onboarding['affected_issue_count'] ?></dd></div></dl><p class="muted">Complete the FleetOS-required information below. The mapping will be created from the authoritative unresolved import issue.</p></section><?php endif; ?>
<?php if ($errors !== []): ?><section class="section import-message tone-danger"><strong>Correct the vehicle information.</strong><ul><?php foreach ($errors as $error): ?><li><?= esc($error) ?></li><?php endforeach; ?></ul></section><?php endif; ?>
<form class="section" action="<?= $editing ? '/fleet/vehicles/' . (int) $vehicle['id'] : '/fleet/vehicles' ?>" method="post"><?= csrf_field() ?>
<?php if ($onboarding !== null): ?><input type="hidden" name="onboarding_turo_vehicle_id" value="<?= esc((string) $onboarding['turo_vehicle_id'], 'attr') ?>"><?php endif; ?>
<div class="section-heading"><p class="eyebrow">FleetOS required</p><h2>Operational Identity</h2></div><div class="issue-filters">
<label>Company<select name="company_id" required><?= $select('company_id', $options['companies']) ?></select></label><label>Fleet number<input name="fleet_number" type="number" min="1" required value="<?= esc((string) $value('fleet_number'), 'attr') ?>" <?= $editing && $vehicle['fleet_number'] !== null ? 'readonly' : '' ?>></label><label>Fleet code<input name="fleet_code" required maxlength="80" value="<?= esc((string) $value('fleet_code'), 'attr') ?>"></label><label>Display name<input name="display_name" required maxlength="150" value="<?= esc((string) $value('display_name'), 'attr') ?>"></label><label>Status<select name="vehicle_status_id" required><?= $select('vehicle_status_id', $options['statuses']) ?></select></label></div>
<div class="section-heading"><p class="eyebrow">Normalized catalog</p><h2>Vehicle Specification</h2></div><div class="issue-filters">
<label>Year<input name="model_year" type="number" min="1900" max="<?= (int) date('Y') + 2 ?>" required value="<?= esc((string) $value('model_year'), 'attr') ?>"></label><label>Make<input name="make_name" required maxlength="120" value="<?= esc((string) $value('make_name'), 'attr') ?>"></label><label>Model<input name="model_name" required maxlength="120" value="<?= esc((string) $value('model_name'), 'attr') ?>"></label><label>Body style<select name="vehicle_body_style_id" required><?= $select('vehicle_body_style_id', $options['body_styles']) ?></select></label><label>Trim<select name="vehicle_trim_level_id" required><?= $select('vehicle_trim_level_id', $options['trim_levels']) ?></select></label><label>Drivetrain<select name="vehicle_drivetrain_id" required><?= $select('vehicle_drivetrain_id', $options['drivetrains']) ?></select></label><label>Exterior color<select name="exterior_vehicle_color_id" required><?= $select('exterior_vehicle_color_id', $options['exterior_colors']) ?></select></label><label>Interior color<select name="interior_vehicle_color_id" required><?= $select('interior_vehicle_color_id', $options['interior_colors']) ?></select></label><label>Seats<input name="seating_capacity" type="number" min="1" max="99" value="<?= esc((string) $value('seating_capacity', 5), 'attr') ?>"></label><label>Powertrain<input name="battery_description" maxlength="120" value="<?= esc((string) $value('battery_description'), 'attr') ?>"></label></div>
<div class="section-heading"><p class="eyebrow">Optional</p><h2>Registration and Service</h2></div><div class="issue-filters"><label>VIN<input name="vin" maxlength="32" value="<?= esc((string) $value('vin'), 'attr') ?>"></label><label>License plate<input name="license_plate" maxlength="32" value="<?= esc((string) $value('license_plate'), 'attr') ?>"></label><label>Acquisition date<input name="purchase_date" type="date" value="<?= esc((string) $value('purchase_date'), 'attr') ?>"></label><label>In-service date<input name="in_service_date" type="date" value="<?= esc((string) $value('in_service_date'), 'attr') ?>"></label><label>Out-of-service date<input name="out_of_service_date" type="date" value="<?= esc((string) $value('out_of_service_date'), 'attr') ?>"></label><label>Odometer miles<input name="odometer_miles" type="number" min="0" value="<?= esc((string) $value('odometer_miles'), 'attr') ?>"></label></div><div class="form-actions"><button class="primary-action" type="submit"><?= $editing ? 'Save Vehicle' : 'Add Vehicle' ?></button></div></form>
<?= view('fleet_command_center/components/footer') ?></main></div><?php if ($assets['js'] !== null): ?><script type="module" src="/build/<?= esc($assets['js'], 'attr') ?>"></script><?php endif; ?></body></html>
