<?php
/** @var array{css: ?string, js: ?string} $assets */
/** @var array<string, mixed> $workflow */
/** @var string|null $notice */
/** @var string|null $error */
?>
<!doctype html>
<html lang="en">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Airport Workflow | FleetOS</title><?php if ($assets['css'] !== null): ?><link rel="stylesheet" href="/build/<?= esc($assets['css'], 'attr') ?>"><?php endif; ?></head>
<body class="fleet-shell">
<main class="command-main import-main">
    <header class="top-status"><div><p class="eyebrow">Airport Workflow</p><h1><?= esc((string) ($workflow['fleet_code'] ?? 'Airport movement')) ?></h1><p class="status-copy"><?= esc(ucfirst((string) ($workflow['movement_type'] ?? 'movement'))) ?> · <?= esc((string) ($workflow['airport_code'] ?? 'HNL')) ?> · <?= esc((string) ($workflow['scheduled_at'] ?? 'Time pending')) ?></p></div><a class="action-link" href="/operations/airport">Airport queue</a></header>
    <?php if ($notice !== null): ?><section class="section import-message tone-success"><strong><?= esc($notice) ?></strong></section><?php endif; ?>
    <?php if ($error !== null): ?><section class="section import-message tone-danger"><strong><?= esc($error) ?></strong></section><?php endif; ?>
    <?php if (! ($workflow['exists'] ?? false)): ?><section class="section"><div class="empty-state">Airport workflow not found.</div></section><?php else: ?>
    <section class="section"><div class="section-heading"><p class="eyebrow">Status</p><h2><?= esc(ucwords(str_replace('_', ' ', (string) $workflow['workflow_status']))) ?></h2></div><dl class="issue-facts"><div><dt>Garage</dt><dd><?= esc((string) ($workflow['garage'] ?? 'Not recorded')) ?></dd></div><div><dt>Level</dt><dd><?= esc((string) ($workflow['parking_level'] ?? 'Not recorded')) ?></dd></div><div><dt>Row</dt><dd><?= esc((string) ($workflow['parking_row'] ?? 'Not recorded')) ?></dd></div><div><dt>Stall</dt><dd><?= esc((string) ($workflow['parking_stall'] ?? 'Not recorded')) ?></dd></div><div><dt>Actual cost</dt><dd><?= esc((string) ($workflow['actual_parking_cost_amount'] ?? 'Not recorded')) ?></dd></div><div><dt>Responsibility</dt><dd><?= esc(ucwords(str_replace('_', ' ', (string) $workflow['parking_cost_responsibility']))) ?></dd></div></dl></section>
    <section class="section"><h2>Staging Details</h2><form class="issue-filters" action="/operations/airport/<?= esc((string) $workflow['id'], 'attr') ?>/staging" method="post"><label>Garage<input name="garage" value="<?= esc((string) ($workflow['garage'] ?? 'HNL International Parking Garage'), 'attr') ?>"></label><label>Level<input name="parking_level" value="<?= esc((string) ($workflow['parking_level'] ?? ''), 'attr') ?>"></label><label>Row<input name="parking_row" value="<?= esc((string) ($workflow['parking_row'] ?? ''), 'attr') ?>"></label><label>Stall<input name="parking_stall" value="<?= esc((string) ($workflow['parking_stall'] ?? ''), 'attr') ?>"></label><label>Entry time<input name="parking_entry_at" type="datetime-local"></label><label>Ticket/access<input name="parking_access_method" value="<?= esc((string) ($workflow['parking_access_method'] ?? ''), 'attr') ?>"></label><button class="primary-action" type="submit">Save Staging</button></form></section>
    <section class="section"><h2>Final Confirmation</h2><form class="resolution-form" action="/operations/airport/<?= esc((string) $workflow['id'], 'attr') ?>/staged" method="post"><label class="checkbox-row"><input type="checkbox" name="vehicle_parked" value="1"><span>Vehicle parked</span></label><label class="checkbox-row"><input type="checkbox" name="vehicle_locked" value="1"><span>Vehicle locked</span></label><label class="checkbox-row"><input type="checkbox" name="key_card_placed" value="1"><span>Key card placed correctly</span></label><label class="checkbox-row"><input type="checkbox" name="parking_details_verified" value="1"><span>Parking details verified</span></label><button class="primary-action" type="submit">Mark Staged</button></form></section>
    <section class="section"><h2>Guest Instructions</h2><?php if ($workflow['instruction']['complete']): ?><p class="muted"><?= esc($workflow['instruction']['text']) ?></p><form action="/operations/airport/<?= esc((string) $workflow['id'], 'attr') ?>/instructions-sent" method="post"><button class="primary-action" type="submit">Mark Instructions Sent</button></form><?php else: ?><div class="empty-state">Instructions incomplete. Missing: <?= esc(implode(', ', $workflow['instruction']['missing'])) ?></div><?php endif; ?></section>
    <section class="section"><h2><?= ($workflow['movement_type'] ?? '') === 'return' ? 'Return Recovery' : 'Guest Pickup' ?></h2><?php if (($workflow['movement_type'] ?? '') === 'return'): ?><form class="issue-filters" action="/operations/airport/<?= esc((string) $workflow['id'], 'attr') ?>/return-location" method="post"><label>Guest level<input name="guest_reported_level"></label><label>Guest row<input name="guest_reported_row"></label><label>Guest stall<input name="guest_reported_stall"></label><label>Guest note<input name="guest_note"></label><button class="primary-action" type="submit">Save Return Location</button></form><form action="/operations/airport/<?= esc((string) $workflow['id'], 'attr') ?>/vehicle-located" method="post"><button class="primary-action" type="submit">Confirm Vehicle Located</button></form><?php else: ?><form action="/operations/airport/<?= esc((string) $workflow['id'], 'attr') ?>/pickup-confirmed" method="post"><button class="primary-action" type="submit">Confirm Guest Pickup</button></form><?php endif; ?></section>
    <section class="section"><h2>Parking Cost</h2><form class="issue-filters" action="/operations/airport/<?= esc((string) $workflow['id'], 'attr') ?>/parking-cost" method="post"><label>Actual cost<input name="actual_parking_cost_amount" inputmode="decimal"></label><label>Responsibility<select name="parking_cost_responsibility"><?php foreach (['host_operational_cost', 'guest_reimbursable', 'included_in_delivery', 'waived', 'unknown'] as $value): ?><option value="<?= esc($value, 'attr') ?>"><?= esc(ucwords(str_replace('_', ' ', $value))) ?></option><?php endforeach; ?></select></label><button class="primary-action" type="submit">Save Cost</button></form></section>
    <section class="section"><h2>Turo Access Override</h2><form class="issue-filters" action="/operations/airport/<?= esc((string) $workflow['id'], 'attr') ?>/turo-access-override" method="post"><label>Incident context<select name="incident_context"><option value="entry">Entry</option><option value="exit">Exit</option><option value="unknown">Unknown</option></select></label><label>Who pulled ticket<select name="operator_type"><option value="guest">Guest</option><option value="host">Host</option><option value="other">Other</option><option value="unknown">Unknown</option></select></label><label>Ticket number<input name="ticket_number"></label><label>Amount paid<input name="parking_amount_paid" inputmode="decimal"></label><label>Note<input name="operator_note"></label><button class="primary-action" type="submit">Parking Ticket Pulled</button></form><p><a class="text-link" href="/operations/airport/reimbursements">Open reimbursement inbox</a></p></section>
    <section class="section"><form action="/operations/airport/<?= esc((string) $workflow['id'], 'attr') ?>/complete" method="post"><button class="primary-action" type="submit">Complete Airport Workflow</button></form><form class="resolution-form" action="/operations/airport/<?= esc((string) $workflow['id'], 'attr') ?>/exception" method="post"><label>Exception type<input name="exception_type" placeholder="vehicle_not_found"></label><label>Note<textarea name="note" rows="3"></textarea></label><button class="secondary-action" type="submit">Record Exception</button></form></section>
    <?php endif; ?>
    <?= view('fleet_command_center/components/footer') ?>
</main>
</body>
</html>
