<?php
/** @var array{css: ?string, js: ?string} $assets */
/** @var array<string, mixed> $workflow */
/** @var string|null $notice */
/** @var string|null $error */
?>
<!doctype html>
<html lang="en">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Airport Workflow | FleetOS</title><?php if ($assets['css'] !== null): ?><link rel="stylesheet" href="/build/<?= esc($assets['css'], 'attr') ?>"><?php endif; ?></head>
<body class="fleet-shell">
<main class="command-main import-main">
    <header class="top-status"><div><p class="eyebrow">Airport Workflow</p><h1><?= esc((string) ($workflow['fleet_code'] ?? 'Airport movement')) ?></h1><p class="status-copy"><?= esc(ucfirst((string) ($workflow['movement_type'] ?? 'movement'))) ?> · <?= esc((string) ($workflow['airport_code'] ?? 'HNL')) ?> · <?= esc((string) ($workflow['scheduled_at'] ?? 'Time pending')) ?></p></div><a class="action-link" href="/operations/airport">Airport queue</a></header>
    <?php if ($notice !== null): ?><section class="section import-message tone-success"><strong><?= esc($notice) ?></strong></section><?php endif; ?>
    <?php if ($error !== null): ?><section class="section import-message tone-danger"><strong><?= esc($error) ?></strong></section><?php endif; ?>
    <?php if (! ($workflow['exists'] ?? false)): ?><section class="section"><div class="empty-state">Airport workflow not found.</div></section><?php else: ?>
    <section class="section"><div class="section-heading"><p class="eyebrow">Status</p><h2><?= esc(ucwords(str_replace('_', ' ', (string) $workflow['workflow_status']))) ?></h2></div><?php if (($workflow['garage_attention'] ?? null) !== null): ?><div class="import-message tone-danger"><strong>Wrong airport garage</strong><p>Recovery / relocation required</p></div><?php endif; ?><dl class="issue-facts"><div><dt>Airport</dt><dd>HNL</dd></div><div><dt>Parking location</dt><dd><?= esc((string) ($workflow['location_label'] ?? 'Not recorded')) ?></dd></div><div><dt>Actual cost</dt><dd><?= esc((string) ($workflow['actual_parking_cost_amount'] ?? 'Not recorded')) ?></dd></div><div><dt>Responsibility</dt><dd><?= esc(ucwords(str_replace('_', ' ', (string) $workflow['parking_cost_responsibility']))) ?></dd></div></dl></section>
    <section class="section"><h2>Staging Details</h2><form class="issue-filters" action="/operations/airport/<?= esc((string) $workflow['id'], 'attr') ?>/staging" method="post"><?= csrf_field() ?><fieldset class="hnl-parking-fields" data-hnl-parking><legend>HNL parking</legend><label>Level<select name="parking_level" data-hnl-level required><option value="">Choose level</option><?php for ($level = 1; $level <= 8; $level++): ?><option value="<?= $level ?>" <?= (string) ($workflow['airport_parking']['level'] ?? '') === (string) $level ? 'selected' : '' ?>><?= $level ?></option><?php endfor; ?></select></label><label>Row<select name="parking_row" data-hnl-row required><option value="">Choose row</option><?php foreach ($workflow['garage_definitions'] as $code => $garage): ?><?php foreach ($garage['rows'] as $row): ?><option value="<?= esc($row, 'attr') ?>" data-garage="<?= esc($code, 'attr') ?>" <?= ($workflow['airport_parking']['row'] ?? '') === $row ? 'selected' : '' ?>><?= esc($row) ?></option><?php endforeach; ?><?php endforeach; ?></select></label><label>Garage<select name="garage" data-hnl-garage required><option value="">Derived from row</option><?php foreach ($workflow['garage_definitions'] as $code => $garage): ?><option value="<?= esc($code, 'attr') ?>" data-max-level="<?= (int) $garage['levels'] ?>" <?= ($workflow['airport_parking']['garage_code'] ?? '') === $code ? 'selected' : '' ?>><?= esc($garage['name']) ?> · <?= esc($garage['color']) ?></option><?php endforeach; ?></select></label></fieldset><label>Entry time<input name="parking_entry_at" type="datetime-local"></label><label>Ticket/access<input name="parking_access_method" value="<?= esc((string) ($workflow['parking_access_method'] ?? ''), 'attr') ?>"></label><label>Note<textarea name="operator_notes" rows="2"><?= esc((string) ($workflow['operator_notes'] ?? '')) ?></textarea></label><button class="primary-action" type="submit">Save Staging</button></form></section>
    <section class="section"><h2>Final Confirmation</h2><?php if (($workflow['movement_type'] ?? '') === 'pickup' && ($workflow['trip_movement_checklist_id'] ?? null) !== null): ?><p class="muted">Record the HNL staging observation on the movement checklist so vehicle state and this workflow stay synchronized.</p><a class="button-link primary-action" href="/operations/checklists/<?= (int) $workflow['trip_movement_checklist_id'] ?>">Open Movement Checklist</a><?php else: ?><form class="resolution-form" action="/operations/airport/<?= esc((string) $workflow['id'], 'attr') ?>/staged" method="post"><?= csrf_field() ?><label class="checkbox-row"><input type="checkbox" name="vehicle_parked" value="1"><span>Vehicle parked</span></label><label class="checkbox-row"><input type="checkbox" name="vehicle_locked" value="1"><span>Vehicle locked</span></label><label class="checkbox-row"><input type="checkbox" name="key_card_placed" value="1"><span>Key card placed correctly</span></label><label class="checkbox-row"><input type="checkbox" name="parking_details_verified" value="1"><span>Parking details verified</span></label><button class="primary-action" type="submit">Mark Staged</button></form><?php endif; ?></section>
    <section class="section"><h2>Guest Instructions</h2><?php if ($workflow['instruction']['complete']): ?><p class="muted"><?= esc($workflow['instruction']['text']) ?></p><form action="/operations/airport/<?= esc((string) $workflow['id'], 'attr') ?>/instructions-sent" method="post"><?= csrf_field() ?><button class="primary-action" type="submit">Mark Instructions Sent</button></form><?php else: ?><div class="empty-state">Instructions incomplete. Missing: <?= esc(implode(', ', $workflow['instruction']['missing'])) ?></div><?php endif; ?></section>
    <section class="section"><h2><?= ($workflow['movement_type'] ?? '') === 'return' ? 'Return Recovery' : 'Guest Pickup' ?></h2><?php if (($workflow['movement_type'] ?? '') === 'return'): ?><p class="muted">Guest-reported HNL location is recorded on the linked return movement as an unverified guest report. This airport workflow does not establish operator possession.</p><?php if (($workflow['trip_movement_checklist_id'] ?? null) !== null): ?><a class="button-link primary-action" href="/operations/checklists/<?= (int) $workflow['trip_movement_checklist_id'] ?>#guest-return-entry">Record guest return report</a><?php endif; ?><form action="/operations/airport/<?= esc((string) $workflow['id'], 'attr') ?>/vehicle-located" method="post"><?= csrf_field() ?><button class="secondary-action" type="submit">Confirm Airport Workflow Vehicle Located</button></form><p class="muted">This airport milestone does not record an authoritative vehicle recovery event. The recovery workflow is planned for Pass 2.</p><?php elseif (($workflow['trip_movement_checklist_id'] ?? null) !== null): ?><a class="button-link primary-action" href="/operations/checklists/<?= (int) $workflow['trip_movement_checklist_id'] ?>">Confirm on Movement Checklist</a><?php endif; ?></section>
    <section class="section"><h2>Parking Cost</h2><form class="issue-filters" action="/operations/airport/<?= esc((string) $workflow['id'], 'attr') ?>/parking-cost" method="post"><?= csrf_field() ?><label>Actual cost<input name="actual_parking_cost_amount" inputmode="decimal"></label><label>Responsibility<select name="parking_cost_responsibility"><?php foreach (['host_operational_cost', 'guest_reimbursable', 'included_in_delivery', 'waived', 'unknown'] as $value): ?><option value="<?= esc($value, 'attr') ?>"><?= esc(ucwords(str_replace('_', ' ', $value))) ?></option><?php endforeach; ?></select></label><button class="primary-action" type="submit">Save Cost</button></form></section>
    <section class="section hnl-policy"><div class="section-heading"><p class="eyebrow">Current HNL policy</p><h2>Gate and parking guidance</h2></div><div class="policy-guidance"><div><h3>Entry</h3><p>Allow the gate to open automatically. If it does not open, pull a parking ticket and leave it visible for the guest.</p></div><div><h3>Host exit after trip</h3><p>Use the staffed exit lane. If the automatic gate fails, show the Turo reservation and parking ticket to the attendant so they can verify the reservation and allow exit without payment.</p></div></div><p>The $<?= esc(number_format((float) ($turoAccessPolicy['host_parking_fee'] ?? 14), 2)) ?> host parking fee is deducted from host earnings as an operating cost. Do not request guest reimbursement.</p><div class="import-message tone-warning"><strong>New Turo Access reimbursement claims are inactive.</strong><p>The former $<?= esc(number_format((float) ($turoAccessPolicy['legacy_cap'] ?? 21), 2)) ?> claim workflow remains available only for historical follow-up.</p></div><p><a class="text-link" href="/operations/airport/reimbursements?filter=action">Open Airport Receipts &amp; Follow-up</a> · <a class="text-link" href="<?= esc((string) ($turoAccessPolicy['reference'] ?? '#'), 'attr') ?>" rel="noreferrer">Policy reference</a></p></section>
    <section class="section"><form action="/operations/airport/<?= esc((string) $workflow['id'], 'attr') ?>/complete" method="post"><?= csrf_field() ?><button class="primary-action" type="submit">Complete Airport Workflow</button></form><form class="resolution-form" action="/operations/airport/<?= esc((string) $workflow['id'], 'attr') ?>/exception" method="post"><?= csrf_field() ?><label>Exception type<input name="exception_type" placeholder="vehicle_not_found"></label><label>Note<textarea name="note" rows="3"></textarea></label><button class="secondary-action" type="submit">Record Exception</button></form></section>
    <?php endif; ?>
    <?= view('fleet_command_center/components/footer') ?>
</main>
<?php if ($assets['js'] !== null): ?><script type="module" src="/build/<?= esc($assets['js'], 'attr') ?>"></script><?php endif; ?>
</body>
</html>
