<?php
/** @var array{css: ?string, js: ?string} $assets */
/** @var array<string, mixed> $inbox */
/** @var string|null $notice */
/** @var string|null $error */
?>
<!doctype html>
<html lang="en">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Airport Reimbursements | FleetOS</title><?php if ($assets['css'] !== null): ?><link rel="stylesheet" href="/build/<?= esc($assets['css'], 'attr') ?>"><?php endif; ?></head>
<body class="fleet-shell"><main class="command-main import-main">
<header class="top-status"><div><p class="eyebrow">Airport Receipt Inbox</p><h1>Airport Receipts</h1><p class="status-copy">Classify airport receipts as trip reimbursement evidence, operations expenses, unresolved, non-business, or duplicate.</p></div><a class="action-link" href="/operations/airport">Airport operations</a></header>
<?php if ($notice !== null): ?><section class="section import-message tone-success"><strong><?= esc($notice) ?></strong></section><?php endif; ?><?php if ($error !== null): ?><section class="section import-message tone-danger"><strong><?= esc($error) ?></strong></section><?php endif; ?>
<section class="section"><div class="section-heading"><p class="eyebrow">Fast Capture</p><h2>Log Airport Run Expense</h2></div><form class="issue-filters" action="/operations/airport/reimbursements/run-expense" method="post" enctype="multipart/form-data"><input type="hidden" name="create_airport_operations_run" value="1"><label>Receipt file<input name="receipt_file" type="file" accept="image/jpeg,image/png,image/webp,application/pdf" capture="environment"></label><label>Expense date<input name="expense_date" type="date"></label><label>Amount<input name="amount" inputmode="decimal"></label><label>Category<select name="expense_category"><option value="parking">Parking</option><option value="fuel">Fuel</option><option value="ev_charging">EV charging</option><option value="car_wash">Car wash</option><option value="supplies">Supplies</option><option value="toll">Toll</option><option value="airport_access_fee">Airport access fee</option><option value="mileage_reimbursement">Mileage</option><option value="other">Other</option></select></label><label>Run date<input name="run_date" type="date"></label><label>Chase vehicle<select name="chase_vehicle_type"><option value="personal_vehicle">Personal vehicle</option><option value="fleet_vehicle">Fleet vehicle</option><option value="company_vehicle">Company vehicle</option><option value="rental_or_borrowed_vehicle">Rental or borrowed</option><option value="other">Other</option></select></label><label>Chase description<input name="chase_vehicle_description"></label><label>Purpose<input name="purpose" value="Airport operations run"></label><label>Business miles<input name="business_miles" inputmode="decimal"></label><label>Business purpose<textarea name="business_purpose_note">Airport operations expense</textarea></label><button class="primary-action" type="submit">Save Run Expense</button></form></section>
<section class="section"><div class="section-heading"><p class="eyebrow">Inbox</p><h2>Incidents</h2></div><div class="mapping-list"><?php if ($inbox['incidents'] === []): ?><div class="empty-state">No unresolved Turo Access reimbursement incidents.</div><?php endif; ?><?php foreach ($inbox['incidents'] as $incident): ?><article class="mapping-card tone-<?= $incident['claim_status'] === 'ready_to_file' ? 'success' : 'warning' ?>"><div class="mapping-card-main"><div><h3><?= esc((string) ($incident['fleet_code'] ?? 'Unknown vehicle')) ?></h3><p>Trip <?= esc((string) ($incident['turo_trip_id'] ?? 'Not linked')) ?> · <?= esc(ucwords(str_replace('_', ' ', (string) $incident['claim_status']))) ?></p></div><dl class="issue-facts"><div><dt>Paid</dt><dd>$<?= esc(number_format((float) ($incident['parking_amount_paid'] ?? 0), 2)) ?></dd></div><div><dt>Expected</dt><dd>$<?= esc(number_format((float) ($incident['expected_reimbursement_amount'] ?? 0), 2)) ?></dd></div><div><dt>Host cost</dt><dd>$<?= esc(number_format((float) ($incident['host_unreimbursed_amount'] ?? 0), 2)) ?></dd></div></dl></div><?php if ($incident['receipts'] !== []): ?><ul class="issue-list"><?php foreach ($incident['receipts'] as $receipt): ?><li><?= esc((string) ($receipt['original_filename'] ?? 'Receipt')) ?><?php if (($receipt['file_id'] ?? null) !== null): ?> · <a class="text-link" href="/files/receipts/<?= esc((string) $receipt['file_id'], 'attr') ?>">Preview</a><?php endif; ?></li><?php endforeach; ?></ul><?php endif; ?><form class="issue-filters" action="/operations/airport/reimbursements/<?= esc((string) $incident['id'], 'attr') ?>/receipt" method="post" enctype="multipart/form-data"><label>Receipt file<input name="receipt_file" type="file" accept="image/jpeg,image/png,image/webp,application/pdf" capture="environment"></label><label>Receipt type<select name="attachment_type"><option value="paid_receipt">Paid receipt</option><option value="parking_ticket">Parking ticket</option><option value="exit_receipt">Exit receipt</option><option value="payment_screenshot">Payment screenshot</option><option value="other_evidence">Other evidence</option></select></label><label>Amount<input name="amount" inputmode="decimal"></label><label>Ticket<input name="ticket_number"></label><button class="primary-action" type="submit">Attach Receipt</button></form><form class="issue-filters" action="/operations/airport/reimbursements/<?= esc((string) $incident['id'], 'attr') ?>/filed" method="post"><label>Claim ref<input name="claim_reference"></label><label>Claimed amount<input name="claimed_amount" inputmode="decimal"></label><button class="secondary-action" type="submit">Mark Filed</button></form></article><?php endforeach; ?></div></section>
<section class="section"><h2>Needs Classification</h2><form class="issue-filters" action="/operations/airport/reimbursements/unmatched-receipt" method="post" enctype="multipart/form-data"><label>Receipt file<input name="receipt_file" type="file" accept="image/jpeg,image/png,image/webp,application/pdf" capture="environment"></label><label>Vehicle ID<input name="fleet_vehicle_id" inputmode="numeric"></label><label>Date<input name="document_date" type="date"></label><label>Amount<input name="amount" inputmode="decimal"></label><label>Ticket<input name="ticket_number"></label><label>Bucket<select name="receipt_classification"><option value="unresolved">Unresolved</option><option value="trip_reimbursement">Trip reimbursement</option><option value="airport_operations_expense">Airport operations expense</option><option value="non_business">Non-business</option><option value="duplicate">Duplicate</option></select></label><button class="primary-action" type="submit">Capture Receipt</button></form><?php if ($inbox['unmatched_receipts'] !== []): ?><div class="mapping-list"><?php foreach ($inbox['unmatched_receipts'] as $receipt): ?><article class="mapping-card tone-warning"><h3><?= esc((string) ($receipt['original_filename'] ?? 'Unmatched receipt')) ?></h3><p><?= esc(ucwords(str_replace('_', ' ', (string) ($receipt['receipt_classification'] ?? 'unresolved')))) ?> · <?= esc((string) ($receipt['document_date'] ?? 'No date')) ?> · $<?= esc(number_format((float) ($receipt['amount'] ?? 0), 2)) ?></p><?php if (($receipt['file_id'] ?? null) !== null): ?><p><a class="text-link" href="/files/receipts/<?= esc((string) $receipt['file_id'], 'attr') ?>">Preview receipt</a></p><?php endif; ?><p><a class="primary-action button-link" href="/operations/airport/reimbursements/match/<?= esc((string) $receipt['id'], 'attr') ?>">Review Matches</a></p></article><?php endforeach; ?></div><?php endif; ?></section>
<?= view('fleet_command_center/components/footer') ?></main></body></html>
