<?php
/** @var array{css: ?string, js: ?string} $assets */
/** @var array<string, mixed> $workspace */
/** @var string|null $notice */
/** @var string|null $error */
$receipt = $workspace['receipt'];
?>
<!doctype html>
<html lang="en">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Classify Airport Receipt | FleetOS</title><?php if ($assets['css'] !== null): ?><link rel="stylesheet" href="/build/<?= esc($assets['css'], 'attr') ?>"><?php endif; ?></head>
<body class="fleet-shell"><main class="command-main import-main">
<header class="top-status"><div><p class="eyebrow">Airport Receipt Inbox</p><h1>Classify Airport Receipt</h1><p class="status-copy">Send the receipt to the right bucket: trip reimbursement, airport operations expense, unresolved, non-business, or duplicate.</p></div><a class="action-link" href="/operations/airport/reimbursements">Inbox</a></header>
<?php if ($notice !== null): ?><section class="section import-message tone-success"><strong><?= esc($notice) ?></strong><p><a class="action-link" href="/operations/airport/reimbursements">Capture Next Receipt</a></p></section><?php endif; ?>
<?php if ($error !== null): ?><section class="section import-message tone-danger"><strong><?= esc($error) ?></strong></section><?php endif; ?>
<?php if (! ($workspace['exists'] ?? false)): ?><section class="section"><div class="empty-state">Receipt not found.</div></section><?php else: ?>
<section class="section receipt-match-layout">
<div class="receipt-panel"><p class="eyebrow">Receipt Evidence</p><h2><?= esc((string) ($receipt['original_filename'] ?? $receipt['file_original_filename'] ?? 'Receipt')) ?></h2><?php if (($receipt['file_id'] ?? null) !== null): ?><div class="receipt-preview"><iframe src="/files/receipts/<?= esc((string) $receipt['file_id'], 'attr') ?>" title="Receipt preview"></iframe></div><?php endif; ?><dl class="issue-facts"><div><dt>Bucket</dt><dd><?= esc(ucwords(str_replace('_', ' ', (string) ($receipt['receipt_classification'] ?? 'unresolved')))) ?></dd></div><div><dt>Date</dt><dd><?= esc((string) ($receipt['document_date'] ?? 'Missing')) ?></dd></div><div><dt>Amount</dt><dd>$<?= esc(number_format((float) ($receipt['amount'] ?? 0), 2)) ?></dd></div><div><dt>Ticket</dt><dd><?= esc((string) ($receipt['ticket_number'] ?? 'Not entered')) ?></dd></div><div><dt>Vehicle</dt><dd><?= esc((string) ($receipt['fleet_vehicle_id'] ?? 'Unknown')) ?></dd></div></dl><form class="issue-filters" action="/operations/airport/reimbursements/receipts/<?= esc((string) $receipt['id'], 'attr') ?>/metadata" method="post"><label>Type<select name="attachment_type"><option value="paid_receipt">Paid receipt</option><option value="parking_ticket">Parking ticket</option><option value="exit_receipt">Exit receipt</option><option value="payment_screenshot">Payment screenshot</option><option value="other_evidence">Other evidence</option></select></label><label>Date<input name="document_date" type="date" value="<?= esc((string) ($receipt['document_date'] ?? ''), 'attr') ?>"></label><label>Amount<input name="amount" inputmode="decimal" value="<?= esc((string) ($receipt['amount'] ?? ''), 'attr') ?>"></label><label>Ticket<input name="ticket_number" value="<?= esc((string) ($receipt['ticket_number'] ?? ''), 'attr') ?>"></label><button class="secondary-action" type="submit">Update Metadata</button></form><div class="classification-actions"><form action="/operations/airport/reimbursements/receipts/<?= esc((string) $receipt['id'], 'attr') ?>/classification" method="post"><input type="hidden" name="receipt_classification" value="unresolved"><button class="secondary-action" type="submit">Leave Unresolved</button></form><form action="/operations/airport/reimbursements/receipts/<?= esc((string) $receipt['id'], 'attr') ?>/classification" method="post"><input type="hidden" name="receipt_classification" value="non_business"><button class="secondary-action" type="submit">Non-Business</button></form><form action="/operations/airport/reimbursements/receipts/<?= esc((string) $receipt['id'], 'attr') ?>/classification" method="post"><input type="hidden" name="receipt_classification" value="duplicate"><button class="secondary-action" type="submit">Duplicate</button></form></div></div>
<div class="candidate-panel"><div class="section-heading"><p class="eyebrow">Trip Reimbursement</p><h2>Suggested Guest Trips</h2></div><form class="issue-filters" method="get"><label>Search<input name="q" value="<?= esc((string) $workspace['query'], 'attr') ?>" placeholder="Spaceship, guest, trip ID"></label><button class="secondary-action" type="submit">Search</button></form><?php if ($workspace['candidates'] === []): ?><div class="empty-state">No trip reimbursement candidates found.</div><?php endif; ?><div class="mapping-list"><?php foreach ($workspace['candidates'] as $candidate): ?><article class="mapping-card tone-<?= $candidate['match_label'] === 'Strong match' ? 'success' : ($candidate['match_label'] === 'Likely match' ? 'warning' : 'info') ?>"><div class="mapping-card-main"><div><span class="status-badge tone-info"><?= esc($candidate['match_label']) ?></span><h3><?= esc((string) ($candidate['fleet_code'] ?? 'Vehicle')) ?></h3><p><?= esc(ucfirst((string) $candidate['movement_type'])) ?> · <?= esc((string) $candidate['scheduled_at']) ?> · <?= esc((string) ($candidate['guest_name'] ?? 'Guest not captured')) ?></p></div><dl class="issue-facts"><div><dt>Trip</dt><dd><?= esc((string) ($candidate['turo_trip_id'] ?? 'N/A')) ?></dd></div><div><dt>Status</dt><dd><?= esc((string) ($candidate['workflow_status'] ?? 'N/A')) ?></dd></div><div><dt>Claim</dt><dd><?= esc((string) ($candidate['existing_claim_status'] ?? 'None')) ?></dd></div></dl></div><ul class="issue-list"><?php foreach ($candidate['reasons'] as $reason): ?><li><?= esc($reason) ?></li><?php endforeach; ?><?php foreach ($candidate['warnings'] as $warning): ?><li><?= esc($warning) ?></li><?php endforeach; ?></ul><details class="issue-details"><summary>Select This Trip</summary><form class="resolution-form" action="/operations/airport/reimbursements/receipts/<?= esc((string) $receipt['id'], 'attr') ?>/match" method="post"><input type="hidden" name="airport_movement_workflow_id" value="<?= esc((string) $candidate['id'], 'attr') ?>"><p class="muted">Creates or reuses a Turo Access reimbursement incident. This does not create an operations expense.</p><button class="primary-action" type="submit">Confirm Trip Reimbursement</button></form></details></article><?php endforeach; ?></div>
<div class="section-heading"><p class="eyebrow">Airport Operations Expense</p><h2>Candidate Runs</h2></div><?php if (($workspace['operation_runs'] ?? []) === []): ?><div class="empty-state">No nearby airport operations run found. Create one below without linking a guest trip.</div><?php endif; ?><div class="mapping-list"><?php foreach (($workspace['operation_runs'] ?? []) as $run): ?><article class="mapping-card tone-info"><div class="mapping-card-main"><div><span class="status-badge tone-info"><?= esc($run['match_label']) ?></span><h3><?= esc((string) $run['purpose']) ?></h3><p><?= esc((string) $run['run_date']) ?> · <?= esc((string) ($run['chase_vehicle_description'] ?? $run['chase_vehicle_type'])) ?></p></div><dl class="issue-facts"><div><dt>Status</dt><dd><?= esc((string) $run['run_status']) ?></dd></div><div><dt>Expenses</dt><dd><?= esc((string) ($run['expense_count'] ?? 0)) ?></dd></div></dl></div><ul class="issue-list"><?php foreach ($run['reasons'] as $reason): ?><li><?= esc($reason) ?></li><?php endforeach; ?></ul><form class="resolution-form" action="/operations/airport/reimbursements/receipts/<?= esc((string) $receipt['id'], 'attr') ?>/operations-expense" method="post"><input type="hidden" name="airport_operations_run_id" value="<?= esc((string) $run['id'], 'attr') ?>"><label>Category<select name="expense_category"><option value="parking">Parking</option><option value="fuel">Fuel</option><option value="ev_charging">EV charging</option><option value="car_wash">Car wash</option><option value="supplies">Supplies</option><option value="toll">Toll</option><option value="airport_access_fee">Airport access fee</option><option value="mileage_reimbursement">Mileage</option><option value="other">Other</option></select></label><label>Business purpose<textarea name="business_purpose_note">Airport operations expense</textarea></label><button class="primary-action" type="submit">Assign To This Run</button></form></article><?php endforeach; ?></div>
<details class="issue-details"><summary>Create New Airport Operations Run</summary><form class="issue-filters" action="/operations/airport/reimbursements/receipts/<?= esc((string) $receipt['id'], 'attr') ?>/operations-expense" method="post"><input type="hidden" name="create_airport_operations_run" value="1"><label>Run date<input name="run_date" type="date" value="<?= esc((string) ($receipt['document_date'] ?? date('Y-m-d')), 'attr') ?>"></label><label>Start time<input name="start_time" type="time"></label><label>End time<input name="end_time" type="time"></label><label>Chase vehicle<select name="chase_vehicle_type"><option value="personal_vehicle">Personal vehicle</option><option value="fleet_vehicle">Fleet vehicle</option><option value="company_vehicle">Company vehicle</option><option value="rental_or_borrowed_vehicle">Rental or borrowed</option><option value="other">Other</option></select></label><label>Chase description<input name="chase_vehicle_description" placeholder="Tacoma, personal car, rental"></label><label>Purpose<input name="purpose" value="Airport operations run"></label><label>Activity<select name="activity_type"><option value="deliver_fleet_vehicle">Deliver fleet vehicle</option><option value="recover_fleet_vehicle">Recover fleet vehicle</option><option value="wash_and_return">Wash and return</option><option value="charge_vehicle">Charge vehicle</option><option value="inspect_vehicle">Inspect vehicle</option><option value="swap_vehicles">Swap vehicles</option><option value="stage_vehicle">Stage vehicle</option><option value="guest_assistance">Guest assistance</option><option value="airport_support">Airport support</option><option value="other">Other</option></select></label><label>Serviced vehicle ID<input name="fleet_vehicle_id" inputmode="numeric" value="<?= esc((string) ($receipt['fleet_vehicle_id'] ?? ''), 'attr') ?>"></label><label>Business miles<input name="business_miles" inputmode="decimal"></label><label>Category<select name="expense_category"><option value="parking">Parking</option><option value="fuel">Fuel</option><option value="ev_charging">EV charging</option><option value="car_wash">Car wash</option><option value="supplies">Supplies</option><option value="toll">Toll</option><option value="airport_access_fee">Airport access fee</option><option value="mileage_reimbursement">Mileage</option><option value="other">Other</option></select></label><label>Business purpose<textarea name="business_purpose_note">Airport operations expense</textarea></label><button class="primary-action" type="submit">Create Run And Assign Receipt</button></form></details></div>
</section>
<?php endif; ?>
</main></body></html>
