<?php
/** @var array{css:?string,js:?string} $assets */
/** @var array<int,array<string,string>> $navigation */
/** @var array<string,mixed> $report */
$money = static fn (float $value): string => ($value < 0 ? '−' : '') . '$' . number_format(abs($value), 2);
$date = static fn (?string $value): string => $value === null ? '—' : (new DateTimeImmutable($value))->format('M j, Y');
$query = static function (string $sort, string $defaultDirection = 'desc') use ($report): string {
    $direction = $report['sort'] === $sort ? ($report['direction'] === 'desc' ? 'asc' : 'desc') : $defaultDirection;

    return '?' . http_build_query(['sort' => $sort, 'direction' => $direction]);
};
?>
<!doctype html>
<html lang="en">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Vehicle Performance | FleetOS</title><?php if ($assets['css'] !== null): ?><link rel="stylesheet" href="/build/<?= esc($assets['css'], 'attr') ?>"><?php endif; ?></head>
<body class="fleet-shell"><a class="skip-link" href="#main-content">Skip to main content</a><div class="app-frame financial-results-frame"><?= view('fleet_command_center/components/navigation', ['items' => $navigation]) ?><main id="main-content" class="command-main operator-main financial-results-main" tabindex="-1">
<header class="top-status financial-results-header"><div><p class="eyebrow">Admin reports</p><h1>Vehicle Performance</h1><p class="status-copy">Realized Turo operating revenue through <?= esc($date($report['as_of_date'])) ?> · Honolulu time</p></div><div class="header-actions"><a class="secondary-action" href="/reports/vehicle-financial-results">Financial Results</a><a class="action-link" href="/#financial-snapshot">Command Center</a></div></header>

<section class="section" aria-labelledby="vehicle-performance-heading"><div class="section-heading split-heading"><div><p class="eyebrow">Earnings by vehicle</p><h2 id="vehicle-performance-heading">Current performance</h2></div><span class="count-pill"><?= (int) $report['vehicle_count'] ?> vehicles</span></div><p class="muted vehicle-performance-context">Month to date begins <?= esc($date($report['month_start'])) ?>. Year to date begins <?= esc($date($report['year_start'])) ?>. Future-dated activity is excluded.</p><div class="financial-table-scroll vehicle-performance-scroll" role="region" aria-label="Vehicle performance report"><table class="financial-results-table vehicle-performance-table"><thead><tr><th scope="col"><a href="<?= esc($query('vehicle', 'asc'), 'attr') ?>">Vehicle</a></th><th scope="col"><a href="<?= esc($query('in_service_date', 'asc'), 'attr') ?>">In Service Date</a></th><th scope="col" class="numeric"><a href="<?= esc($query('mtd'), 'attr') ?>">MTD Earnings</a></th><th scope="col" class="numeric"><a href="<?= esc($query('ytd'), 'attr') ?>">YTD Earnings</a></th><th scope="col" class="numeric"><a href="<?= esc($query('lifetime'), 'attr') ?>">Lifetime Earnings</a></th></tr></thead><tbody><?php foreach ($report['rows'] as $row): ?><tr<?= $row['is_unallocated'] ? ' class="unallocated-revenue-row"' : '' ?>><th scope="row" data-label="Vehicle"><?php if ($row['fleet_vehicle_id'] !== null): ?><a class="text-link" href="/fleet/vehicles/<?= (int) $row['fleet_vehicle_id'] ?>"><?= esc((string) $row['vehicle_label']) ?></a><?php else: ?><span><?= esc((string) $row['vehicle_label']) ?></span><small>Revenue retained for reconciliation</small><?php endif; ?><?php if ($row['fleet_number'] !== null): ?><small>Fleet #<?= (int) $row['fleet_number'] ?></small><?php endif; ?></th><td data-label="In Service Date"><?= esc($date($row['in_service_date'])) ?></td><td class="numeric" data-label="MTD Earnings"><?= esc($money((float) $row['mtd_earnings'])) ?></td><td class="numeric" data-label="YTD Earnings"><?= esc($money((float) $row['ytd_earnings'])) ?></td><td class="numeric result-value" data-label="Lifetime Earnings"><?= esc($money((float) $row['lifetime_earnings'])) ?></td></tr><?php endforeach; ?></tbody><tfoot><tr><th scope="row" data-label="Vehicle">Fleet total</th><td data-label="In Service Date">—</td><td class="numeric" data-label="MTD Earnings"><?= esc($money((float) $report['totals']['mtd_earnings'])) ?></td><td class="numeric" data-label="YTD Earnings"><?= esc($money((float) $report['totals']['ytd_earnings'])) ?></td><td class="numeric result-value" data-label="Lifetime Earnings"><?= esc($money((float) $report['totals']['lifetime_earnings'])) ?></td></tr></tfoot></table></div><?php if ($report['has_unallocated']): ?><p class="reconciliation-note">Unallocated / Unmatched preserves valid company revenue associated with a vehicle outside the current report roster so displayed rows reconcile to company totals.</p><?php endif; ?></section>
<?= view('fleet_command_center/components/footer') ?></main></div><?php if ($assets['js'] !== null): ?><script type="module" src="/build/<?= esc($assets['js'], 'attr') ?>"></script><?php endif; ?></body></html>
