<?php $area ??= []; $prefix ??= 'area'; $existingConditions = []; foreach (array_merge($vehicleDamage['current'], $vehicleDamage['history'] ?? [], $vehicleDamage['related'] ?? []) as $condition) { $existingConditions[(int) $condition['id']] = $condition; } ?>
<fieldset class="mapping-card damage-area"><legend>Damage area</legend><div class="damage-form-grid issue-filters">
<label>Panel<select name="<?= esc($prefix, 'attr') ?>[panel_code]" required><option value="">Choose panel</option><?php foreach (\Config\VehicleDamage::PANELS as $code => $label): ?><option value="<?= esc($code, 'attr') ?>"<?= ($area['panel_code'] ?? '') === $code ? ' selected' : '' ?>><?= esc($label) ?></option><?php endforeach; ?></select></label>
<label>Damage type<select name="<?= esc($prefix, 'attr') ?>[damage_type_code]" required><?php foreach (\App\Services\Fleet\VehicleDamageService::DAMAGE_TYPES as $code => $label): ?><option value="<?= esc($code, 'attr') ?>"<?= ($area['damage_type_code'] ?? '') === $code ? ' selected' : '' ?>><?= esc($label) ?></option><?php endforeach; ?></select></label>
<label>Severity<select name="<?= esc($prefix, 'attr') ?>[severity_code]" required><?php foreach (\App\Services\Fleet\VehicleDamageService::SEVERITIES as $code => $label): ?><option value="<?= esc($code, 'attr') ?>"<?= ($area['severity_code'] ?? '') === $code ? ' selected' : '' ?>><?= esc($label) ?></option><?php endforeach; ?></select></label>
<label>Effect<select name="<?= esc($prefix, 'attr') ?>[effect_code]" required><?php foreach (\Config\VehicleDamage::EFFECTS as $code => $label): ?><option value="<?= esc($code, 'attr') ?>"<?= ($area['effect_code'] ?? '') === $code ? ' selected' : '' ?>><?= esc($label) ?></option><?php endforeach; ?></select></label>
<label>Existing condition (worsening needs a current condition)<select name="<?= esc($prefix, 'attr') ?>[vehicle_damage_item_id]"><option value="">New condition</option><?php foreach ($existingConditions as $condition): ?><option value="<?= (int) $condition['id'] ?>"<?= (int) ($area['vehicle_damage_item_id'] ?? 0) === (int) $condition['id'] ? ' selected' : '' ?>>#<?= (int) $condition['id'] ?> · <?= esc((string) ($condition['panel_label'] ?? $condition['zone_label'])) ?> · <?= esc((string) $condition['description']) ?> · <?= esc((string) $condition['severity_label']) ?><?php if (($condition['current_condition_item_id'] ?? null) !== null): ?> · Historical → #<?= (int) $condition['current_condition_item_id'] ?><?php else: ?> · <?= esc((string) $condition['status_code']) ?><?php endif; ?></option><?php endforeach; ?></select></label>
<label>Area note / description<textarea name="<?= esc($prefix, 'attr') ?>[note]" required maxlength="2000" rows="2"><?= esc((string) ($area['note'] ?? '')) ?></textarea></label>
</div><details><summary>Optional evidence for this area</summary><div class="damage-form-grid issue-filters">
<label>Existing private vehicle file ID<input type="number" min="1" name="<?= esc($prefix, 'attr') ?>[file_id]" value="<?= esc((string) ($area['file_id'] ?? ''), 'attr') ?>"></label>
<label>Existing private vehicle image ID<input type="number" min="1" name="<?= esc($prefix, 'attr') ?>[image_id]" value="<?= esc((string) ($area['image_id'] ?? ''), 'attr') ?>"></label>
<label>External reference (text only)<input maxlength="500" name="<?= esc($prefix, 'attr') ?>[external_reference]" value="<?= esc((string) ($area['external_reference'] ?? ''), 'attr') ?>"></label>
</div><p>Supply one evidence reference per area. Stored files and images must belong to this vehicle.</p></details>
<button type="button" class="secondary-action" data-remove-damage-area>Remove area</button></fieldset>
