<?php $base = '/fleet/vehicles/' . (int) $vehicle['id'] . '/damage/' . (int) $source['id']; $formData ??= []; $canLink = ! ($sourceHasWork ?? false) && ($source['current_condition_item_id'] ?? null) === null && ! array_any($vehicleDamage['related'] ?? [], static fn (array $record): bool => (int) $record['current_condition_item_id'] === (int) $source['id']) && $target !== null && (int) $source['id'] !== (int) $target['id'] && ($target['current_condition_item_id'] ?? null) === null && in_array($target['status_code'], ['open', 'accepted_unrepaired'], true); ?>
<section class="section"><h1>Link as worsened existing damage</h1>
<form action="<?= $base ?>/link-preview" method="get"><label>Canonical target<select name="target_id" required><option value="">Choose existing condition</option><?php foreach ($vehicleDamage['current'] as $condition): ?><?php if ((int) $condition['id'] === (int) $source['id']) { continue; } ?><option value="<?= (int) $condition['id'] ?>"<?= (int) ($target['id'] ?? 0) === (int) $condition['id'] ? ' selected' : '' ?>>#<?= (int) $condition['id'] ?> · <?= esc((string) $condition['description']) ?></option><?php endforeach; ?></select></label><button class="secondary-action" type="submit">Preview relationship</button></form>
<?php if ($sourceHasWork ?? false): ?><p role="alert">This condition has repair/work history and must remain canonical. Retargeting that history is unavailable.</p><?php endif; ?>
<?php if ($target !== null && ! $canLink): ?><p role="alert">This relationship cannot be confirmed. Choose a different current canonical target; the source must have no existing historical relationships.</p><?php endif; ?>
<?php if ($canLink): ?><div class="damage-update-grid">
<?php foreach (['Source / historical item' => [$source, $sourceEvidenceCount], 'Canonical target item' => [$target, $targetEvidenceCount]] as $heading => [$record, $count]): ?>
<article class="mapping-card"><h2><?= esc($heading) ?> #<?= (int) $record['id'] ?></h2><p><?= esc(\Config\VehicleDamage::PANELS[$record['panel_code'] ?? ''] ?? (string) $record['zone_code']) ?></p><p><?= nl2br(esc((string) $record['description'])) ?></p>
<p><?= esc(\App\Services\Fleet\VehicleDamageService::SEVERITIES[$record['severity_code']]) ?> · <?= esc((string) $record['status_code']) ?></p><p>Discovered <?= esc((string) $record['discovered_at']) ?> · Trip <?= esc((string) ($record['turo_reservation_id'] ?? 'Not linked')) ?></p><p><?= $count ?> evidence references</p></article>
<?php endforeach; ?></div>
<p>Condition #<?= (int) $target['id'] ?> remains canonical. The source ID, discovery, evidence and history remain accessible. Target severity will retain the higher severity.</p>
<p>Current condition count: <?= count($vehicleDamage['current']) ?> → <?= count($vehicleDamage['current']) - (in_array($source['status_code'], ['open', 'accepted_unrepaired'], true) && empty($source['current_condition_item_id']) ? 1 : 0) ?>.</p>
<form action="<?= $base ?>/link" method="post"><?= csrf_field() ?>
<input type="hidden" name="target_id" value="<?= (int) $target['id'] ?>"><input type="hidden" name="source_state" value="<?= esc(\App\Services\Fleet\VehicleDamageIncidentService::fingerprint($source), 'attr') ?>"><input type="hidden" name="target_state" value="<?= esc(\App\Services\Fleet\VehicleDamageIncidentService::fingerprint($target), 'attr') ?>">
<label>Relationship reason<textarea name="reason" required maxlength="2000"><?= esc((string) ($formData['reason'] ?? '')) ?></textarea></label><label><input type="checkbox" name="confirmed" value="1" required> I confirm this source records worsening of the selected canonical condition.</label><button class="primary-action" type="submit">Link as worsened existing damage</button></form>
<?php endif; ?></section>
