<?php $base = '/fleet/vehicles/' . (int) $vehicle['id']; $formData ??= []; ?>
<section class="section"><h1>Damage incident #<?= (int) $incident['id'] ?></h1>
<dl class="issue-facts"><div><dt>Discovered</dt><dd><?= esc((string) $incident['discovered_at']) ?></dd></div><div><dt>Occurred</dt><dd><?= esc((string) ($incident['occurred_at'] ?? 'Not recorded')) ?></dd></div>
<div><dt>Reservation / trip</dt><dd><?= esc((string) ($incident['turo_reservation_id'] ?? 'Unknown')) ?></dd></div><div><dt>Attribution</dt><dd><?= esc(\Config\VehicleDamage::ATTRIBUTIONS[$incident['attribution_type']] ?? $incident['attribution_type']) ?></dd></div>
<div><dt>Recorded by</dt><dd>Operator #<?= (int) $incident['created_by'] ?> · <?= esc((string) $incident['created_at']) ?></dd></div></dl>
<p><?= nl2br(esc((string) $incident['overall_note'])) ?></p><h2>Damage areas / history</h2>
<details class="capital-disclosure"><summary>Incident audit history</summary><ol class="damage-history"><?php foreach ($incidentHistory ?? [] as $change): ?><?php $before = json_decode((string) $change['old_values'], true) ?? []; $after = json_decode((string) $change['new_values'], true) ?? []; ?><li>Operator #<?= (int) $change['actor_user_id'] ?> · <?= esc((string) $change['created_at']) ?><p><?= esc((string) ($after['reason'] ?? 'Incident recorded')) ?></p><p>Trip <?= esc((string) ($before['turo_trip_normalized_id'] ?? 'Unknown')) ?> → <?= esc((string) ($after['turo_trip_normalized_id'] ?? 'Unknown')) ?> · <?= esc(\Config\VehicleDamage::ATTRIBUTIONS[$after['attribution_type'] ?? 'unknown']) ?></p></li><?php endforeach; ?></ol></details>
<div class="mapping-list"><?php foreach ($memberships as $membership): ?><article class="mapping-card"><h3><?= esc(\Config\VehicleDamage::PANELS[$membership['panel_code'] ?? ''] ?? 'Legacy panel not specified') ?></h3>
<p><?= esc(\Config\VehicleDamage::EFFECTS[$membership['effect_code']]) ?> · <?= esc(\App\Services\Fleet\VehicleDamageService::DAMAGE_TYPES[$membership['damage_type_code']]) ?> · <?= esc(\App\Services\Fleet\VehicleDamageService::SEVERITIES[$membership['severity_code']]) ?></p>
<p><?= nl2br(esc((string) $membership['note'])) ?></p><p>Operator #<?= (int) $membership['created_by'] ?> · <?= esc((string) $membership['created_at']) ?></p>
<a href="<?= $base ?>/damage/<?= (int) $membership['vehicle_damage_item_id'] ?>">Condition #<?= (int) $membership['vehicle_damage_item_id'] ?>: history and evidence</a>
<?php if ($membership['current_condition_item_id'] !== null): ?><p>Historical provenance for canonical condition #<?= (int) $membership['current_condition_item_id'] ?></p><?php endif; ?></article><?php endforeach; ?></div>
<details class="capital-disclosure"><summary>Add / correct trip attribution</summary><form action="<?= $base ?>/damage-incidents/<?= (int) $incident['id'] ?>/trip" method="post"><?= csrf_field() ?>
<input type="hidden" name="expected_state" value="<?= esc(\App\Services\Fleet\VehicleDamageIncidentService::fingerprint($incident), 'attr') ?>">
<div class="damage-form-grid issue-filters"><label>Reservation / trip<select name="trip_id" required><option value="">Choose trip</option><?php foreach ($trips as $trip): ?><option value="<?= (int) $trip['id'] ?>"<?= (int) ($formData['trip_id'] ?? $incident['turo_trip_normalized_id']) === (int) $trip['id'] ? ' selected' : '' ?>><?= esc((string) $trip['turo_reservation_id']) ?></option><?php endforeach; ?></select></label>
<label>Attribution meaning<select name="attribution_type"><?php foreach (\Config\VehicleDamage::ATTRIBUTIONS as $code => $label): ?><option value="<?= esc($code, 'attr') ?>"<?= ($formData['attribution_type'] ?? $incident['attribution_type']) === $code ? ' selected' : '' ?>><?= esc($label) ?></option><?php endforeach; ?></select></label>
<label>Reason<textarea name="reason" required maxlength="2000"><?= esc((string) ($formData['reason'] ?? '')) ?></textarea></label></div><button class="secondary-action" type="submit">Save attribution</button></form></details>
<details class="capital-disclosure"><summary>Attach another damage area</summary><form action="<?= $base ?>/damage-incidents/<?= (int) $incident['id'] ?>/areas" method="post"><?= csrf_field() ?>
<?= view('vehicle_damage_incidents/_areas', ['area' => is_array($formData['area'] ?? null) ? $formData['area'] : [], 'prefix' => 'area']) ?><button class="secondary-action" type="submit">Attach area</button></form></details>
</section>
